include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true

    avoid_classes_with_only_static_members: false

    sort_constructors_first: true

    prefer_single_quotes: true

    always_specify_types: false

    lines_longer_than_80_chars: true

    type_annotate_public_apis: false

    directives_ordering: true

    ### Documentation ###

    slash_for_doc_comments: true

    comment_references: true

    prefer_const_literals_to_create_immutables: false

    avoid_setters_without_getters: false
