name: katex_flutter
description: Performantly render scientific LaTeX equations using the KaTeX library on Android, iOS, the Web and the Desktop platform.
version: 4.0.2+26
homepage: https://gitlab.com/testapp-system/katex_flutter
respsitory: https://gitlab.com/testapp-system/katex_flutter.git
issue_tracker: https://gitlab.com/testapp-system/katex_flutter/issues

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  catex: ^0.0.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter
