name: katex_flutter
description: Performantly render scientific LaTeX equations using the KaTeX library on Android, iOS, the Web and the Desktop platform.

publish_to: "none"

version: 5.0.3+2
homepage: https://gitlab.com/testapp-system/katex_flutter
respsitory: https://gitlab.com/testapp-system/katex_flutter.git
issue_tracker: https://gitlab.com/testapp-system/katex_flutter/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork:
    git:
      url: https://github.com/simpleclub-extended/flutter_math.git
dev_dependencies:
  lint: ^1.5.2
