name: katex_flutter
description: Performantly render scientific LaTeX equations on all platforms.
publish_to: "none"
version: 5.3.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.0
